### ISSUE TITLE
manny mua, nikkita dragun

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/apology#24]
missing people?

**Comment by russellsamora** [comment]
https://www.vox.com/2018/8/28/17769996/laura-lee-jeffree-star-racism-subscriber-count

**Comment by russellsamora** [comment]
maybe supplement scraping with google search
https://www.google.com/search?q=ranking+youtube+apology+videos&oq=ranking+youtube+apology+videos&aqs=chrome..69i57j33.3408j0j1&sourceid=chrome&ie=UTF-8

**Comment by russellsamora** [comment]
https://www.youtube.com/watch?v=3jZDt5zQWsE&feature=emb_title

**Comment by arjunkakkar8** [comment]
Shane is actually in the final list, but we don't have data for him because the video is too old.

**Comment by arjunkakkar8** [comment]
Added three new apologies after manual search
